Added multiple tools
psiinon/open-source-web-scanners pull request #13
Opened 2024-08-10 12:18 UTC by 0x-Apollyon

Added multiple tools such as
--> Katana: High speed webcrawler
--> Amass: Recon tool by the OWASP foundation
--> NoSQLMap: SQLMap like tool for NoSQL databases
--> Ghauri: Sql Injection scanner
--> Gxss: Reflection checker

2024-08-12 13:57 UTC, psiinon commented
Katana - right now I'm not including just crawlers as there are too many :) See https://github.com/BruceDone/awesome-crawler
Amass - likewise attack surface management, this is just for attacking web apps
The other 3 look good though..

2024-08-12 13:58 UTC, psiinon requested changes
As per other comment :)

2024-08-12 23:42 UTC, 0x-Apollyon commented
Did the changes as requested

2024-08-13 08:02 UTC, psiinon approved these changes

2024-08-13 08:02 UTC, merged